export interface BuiltinVar {
  name: string;
  type: string;
  doc: string;
}

export const BUILTIN_VARS: BuiltinVar[] = [
  { name: 'iTime', type: 'float', doc: '当前播放时间（秒），从 0 递增。' },
  { name: 'iTimeDelta', type: 'float', doc: '上一帧到当前帧的时间间隔（秒）。' },
  { name: 'iFrame', type: 'int', doc: '帧序号，从 0 开始递增。' },
  { name: 'iResolution', type: 'vec3', doc: '渲染分辨率，z 分量通常为 1。' },
  { name: 'iMouse', type: 'vec4', doc: '鼠标状态：xy=按下时坐标，zw=当前坐标（画布像素）。' },
  { name: 'iDate', type: 'vec4', doc: '当前日期：x=年, y=月, z=日, w=秒（含小数）。' },
  { name: 'iSampleRate', type: 'float', doc: '音频采样率（默认 44100），仅 Sound Pass 使用。' },
  { name: 'iChannel0', type: 'sampler2D', doc: '输入纹理/缓冲通道 0。' },
  { name: 'iChannel1', type: 'sampler2D', doc: '输入纹理/缓冲通道 1。' },
  { name: 'iChannel2', type: 'sampler2D', doc: '输入纹理/缓冲通道 2。' },
  { name: 'iChannel3', type: 'sampler2D', doc: '输入纹理/缓冲通道 3。' },
  { name: 'iChannelResolution', type: 'vec3[4]', doc: '各通道的纹理分辨率。' },
  { name: 'iChannelTime', type: 'float[4]', doc: '各通道纹理的播放时间。' },
  { name: 'iPi', type: 'const float', doc: '圆周率 π（3.14159265359）。' },
  { name: 'iTau', type: 'const float', doc: '2π（6.28318530718）。' },
  { name: 'gl_FragCoord', type: 'vec4', doc: '当前片元的窗口坐标（像素中心）。' },
  { name: 'gl_FrontFacing', type: 'bool', doc: '片元是否为正面朝向。' },
];

export interface BuiltinFunc {
  sig: string;
  doc: string;
}

export const BUILTIN_FUNCS: Record<string, BuiltinFunc> = {
  texture: { sig: 'vec4 texture(sampler2D sampler, vec2 P [, float bias])', doc: '从 2D 纹理采样，P 为归一化坐标。' },
  textureLod: { sig: 'vec4 textureLod(sampler2D sampler, vec2 P, float lod)', doc: '指定 LOD 层级采样纹理。' },
  textureProj: { sig: 'vec4 textureProj(sampler2D sampler, vec3 P)', doc: '投影采样（P.xy / P.z）。' },
  textureSize: { sig: 'ivec2 textureSize(sampler2D sampler, int lod)', doc: '查询纹理在指定 LOD 的尺寸。' },
  texelFetch: { sig: 'vec4 texelFetch(sampler2D sampler, ivec2 P, int lod)', doc: '直接按整数像素坐标取纹素。' },
  sin: { sig: 'float sin(float x)', doc: '正弦。' },
  cos: { sig: 'float cos(float x)', doc: '余弦。' },
  tan: { sig: 'float tan(float x)', doc: '正切。' },
  asin: { sig: 'float asin(float x)', doc: '反正弦，返回弧度。' },
  acos: { sig: 'float acos(float x)', doc: '反余弦，返回弧度。' },
  atan: { sig: 'float atan(float y, float x)', doc: '反正切（双参重载更稳）。' },
  pow: { sig: 'float pow(float x, float y)', doc: 'x 的 y 次幂。' },
  exp: { sig: 'float exp(float x)', doc: '自然指数 e^x。' },
  exp2: { sig: 'float exp2(float x)', doc: '2 的 x 次幂。' },
  log: { sig: 'float log(float x)', doc: '自然对数。' },
  log2: { sig: 'float log2(float x)', doc: '以 2 为底的对数。' },
  sqrt: { sig: 'float sqrt(float x)', doc: '平方根。' },
  inversesqrt: { sig: 'float inversesqrt(float x)', doc: '平方根的倒数。' },
  abs: { sig: 'float abs(float x)', doc: '绝对值（向量重载按分量）。' },
  sign: { sig: 'float sign(float x)', doc: '符号函数。-1/0/1。' },
  floor: { sig: 'float floor(float x)', doc: '向下取整。' },
  ceil: { sig: 'float ceil(float x)', doc: '向上取整。' },
  trunc: { sig: 'float trunc(float x)', doc: '向零取整。' },
  round: { sig: 'float round(float x)', doc: '四舍五入。' },
  fract: { sig: 'float fract(float x)', doc: '小数部分（x - floor(x)）。' },
  mod: { sig: 'float mod(float x, float y)', doc: '取模（结果为 x - y*floor(x/y)）。' },
  modf: { sig: 'float modf(float x, out float i)', doc: '拆分整数与小数部分。' },
  min: { sig: 'float min(float a, float b)', doc: '取较小值。' },
  max: { sig: 'float max(float a, float b)', doc: '取较大值。' },
  clamp: { sig: 'float clamp(float x, float minVal, float maxVal)', doc: '限制到 [minVal, maxVal]。' },
  mix: { sig: 'float mix(float a, float b, float t)', doc: '线性插值：a*(1-t) + b*t。' },
  step: { sig: 'float step(float edge, float x)', doc: '阶梯函数：x<edge 返回 0 否则 1。' },
  smoothstep: { sig: 'float smoothstep(float e0, float e1, float x)', doc: '平滑阶梯插值（Hermite）。' },
  length: { sig: 'float length(vec2 v)', doc: '向量长度（模长）。' },
  distance: { sig: 'float distance(vec2 a, vec2 b)', doc: '两点距离。' },
  dot: { sig: 'float dot(vec2 a, vec2 b)', doc: '点积。' },
  cross: { sig: 'vec3 cross(vec3 a, vec3 b)', doc: '叉积。' },
  normalize: { sig: 'vec2 normalize(vec2 v)', doc: '归一化向量。' },
  faceforward: { sig: 'vec3 faceforward(vec3 N, vec3 I, vec3 Nref)', doc: '反射向量翻转。' },
  reflect: { sig: 'vec3 reflect(vec3 I, vec3 N)', doc: '反射方向。' },
  refract: { sig: 'vec3 refract(vec3 I, vec3 N, float eta)', doc: '折射方向。' },
  matrixCompMult: { sig: 'mat2 matrixCompMult(mat2 a, mat2 b)', doc: '矩阵逐分量相乘（非矩阵乘法）。' },
  outerProduct: { sig: 'mat2 outerProduct(vec2 c, vec2 r)', doc: '外积（列×行）。' },
  transpose: { sig: 'mat2 transpose(mat2 m)', doc: '矩阵转置。' },
  determinant: { sig: 'float determinant(mat2 m)', doc: '矩阵行列式。' },
  inverse: { sig: 'mat2 inverse(mat2 m)', doc: '矩阵求逆。' },
  lessThan: { sig: 'bvec2 lessThan(vec2 a, vec2 b)', doc: '逐分量小于比较。' },
  equal: { sig: 'bvec2 equal(vec2 a, vec2 b)', doc: '逐分量相等比较。' },
  notEqual: { sig: 'bvec2 notEqual(vec2 a, vec2 b)', doc: '逐分量不等比较。' },
  any: { sig: 'bool any(bvec2 v)', doc: '任意分量为 true。' },
  all: { sig: 'bool all(bvec2 v)', doc: '全部分量为 true。' },
  not: { sig: 'bvec2 not(bvec2 v)', doc: '逐分量取反。' },
  dFdx: { sig: 'float dFdx(float p)', doc: 'x 方向的偏导数（像素导数）。' },
  dFdy: { sig: 'float dFdy(float p)', doc: 'y 方向的偏导数。' },
  fwidth: { sig: 'float fwidth(float p)', doc: 'abs(dFdx) + abs(dFdy)。' },
  noise1: { sig: 'float noise1(genType x)', doc: '内置噪声函数（未定义时请用自定义噪声）。' },
};